version: '2'
services:
  haproxy:
    image: kontena/haproxy:latest
    environment:
      - SSL_CERT
      - BACKEND_PORT=9292
    ports:
      - 8080:80
      - 8443:443
    networks:
      - kontena
  api:
    image: kontena/server:latest
    environment:
      - RACK_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/kontena
    networks:
      kontena:
        aliases:
          - kontena-server-api
  mongodb:
    image: mongo:3.0
    command: mongod --smallfiles
    volumes:
      - kontena-server-mongodb:/data/db
    networks:
      - kontena
networks:
  kontena:
    driver: bridge
volumes:
  kontena-server-mongodb:
    driver: local
